AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template Definition
Globals:
  Function:
    Environment:
      Variables:
        db_host: DEVOPS-PLAYGROUND-DB-HOST
        db_read_host: DEVOPS-PLAYGROUND-DB-HOST
        db_user: DEVOPS-PLAYGROUND-DB-USER
        db_pswd: DEVOPS-PLAYGROUND-DB-PSWD
        db: DEVOPS-PLAYGROUND-DB

  PlatformConsumer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app/platform_consumer.lambda_handler
      Runtime: python3.9
      FunctionName: PlatformConsumerProd
      MemorySize: 512
      Timeout: 900
      Policies:
        - AmazonSSMFullAccess
        - AmazonSQSFullAccess
      Events:
        SQSEventForUser:
          Type: SQS
          Properties:
            Queue: 'arn:aws:sqs:eu-west-1:727804883967:platform-data-aggregation-test'
            BatchSize: 10
            Enabled: true
      Environment:
        Variables:
          log_grp: testloggroup
          log_stream: platform-consumer
