AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template Definition
Globals:
  Function:
    Environment:
      Variables:
        consumer_key: consumer_key
        consumer_secret: consumer_secret
        bearer_token: bearer_token
        access_token: access_token
        token_secret: token_secret
        twitter_base_url: "https://api.twitter.com/2/"
Resources:
  ELevyBot:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app/main.lambda_handler
      Runtime: python3.8
      FunctionName: e_levy_bot
      MemorySize: 512
      Timeout: 900
      Policies:
        - AmazonSSMFullAccess
